### ISSUE TITLE
[BUG] Some people in the room cannot be heard

### ISSUE THREAD

**Issue by MatadorProBr** [cybershard/auproximity#10]
**Describe the bug**
When a lot of people are in a room together, eventually some people can't hear you or you can't hear.

**To Reproduce**
1. Go to the website and put your name and code right.
2. Call your friends or people.
3. Here will be the error, some will hear you, or you will not hear some.

**Expected behaviour**
I can hear everyone and everyone can hear me.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Browser [microsoft edge]
 - Version [87.0.664.47]

**Smartphone (please complete the following information):**
N/A

**Additional context**
I think I already showed everything and I don't need to describe the bug anymore.

**Comment by JohnClementine** [comment]
Just to clarify, you're saying that some people are not able to hear other or be heard in auproximity? Have you had them try another browser and confirm that they select allow when being asked if the site can have permission to control their microphone?

**Comment by MatadorProBr** [comment]
> Só para esclarecer, você está dizendo que algumas pessoas não são capazes de ouvir outras e ser ouvidas em auproximidade? Você já os fez experimentar outro navegador e confirmar que eles selecionam permitir ao ser perguntado se o site pode ter permissão para controlar seu microfone?

Yes and yes, I tested it with Chrome and it had given the same thing and everyone allowed the microphone.

**Comment by cybershard** [comment]
@MatadorProBr, can you try with the dev server https://auproxydev.herokuapp.com, and test if it still breaks?
I also have a few questions:
- Your issue is that when a lot of people connect, some people cannot hear each other? 
- Does this issue always happen with the same people?
- Can the people with the issue hear other people, or can they not hear anyone at all? 
- Can the people for whom the proximity voice works, hear the people for whom it is broken?

**Comment by rgar22** [comment]
I have same issue, additionally dead cremates can be heard by players at all times. this was with the version kindly hosted on https://auproxy.herokuapp.com/

**Comment by MatadorProBr** [comment]
> @MatadorProBr, can you try with the dev server https://auproxydev.herokuapp.com, and test if it still breaks?
Okay, later I will test with my friends.
> I also have a few questions:
> 
> * Your issue is that when a lot of people connect, some people cannot hear each other?
Yes.
> * Does this issue always happen with the same people?
Yes, I had even called a few more people, but even then the bug was still with the new people.
> * Can the people with the issue hear other people, or can they not hear anyone at all?
They can hear people, but some cannot be heard by some people, like I can hear the person but not someone else.
> * Can the people for whom the proximity voice works, hear the people for whom it is broken?
No.

**Comment by cybershard** [comment]
Try with the newest update

**Comment by gr01d** [comment]
Is the issue resolved?

**Comment by gr01d** [comment]
We tested the dev site this night and they cannot hear me but some of they hear one another.

**Comment by cybershard** [comment]
This has been fixed for most people, but please continue the conversation on the Discord: https://discord.gg/gvQzM4GYbv

**Comment by angelaqiu** [comment]
We had this same problem but found out that if everyone refreshes or clicks Join again _after_ everyone joins, then everyone can hear everyone. If someone joins and others don't refresh then they usually can't hear that person.

**Comment by gr01d** [comment]
I am not sure whether to use the dev site or the normal auproxy, do they work on both of them?

Steps to make it work (correct me if I miss something):
1. Create room for game
2. join the game with your chosen name
2. open the herokuapp, input room code and your character name click join
4. reload the page? this will make you re enter the room code and character name?
