### ISSUE TITLE
[BUG] iOS Safari connection.

### ISSUE THREAD

**Issue by KronosTheMighty** [cybershard/auproximity#12]
**Describe the bug**
When an iOS user tries to connect to a proximity chat group, they show that the microphone is being used, however, they show up as disconnected in both their and the other people's screens.
**To Reproduce**
1. Go to the proximity chat website on ios safari
2. Put in the required data
3. Look at your name and see disconnected

**Expected behavior**
What is expected to happen is having the "connected" sign show up next to your name, with the volume setting for your microphone.

**Where are you using the proximity chat?:**
 - Browser=safari
 - Platform=ios

**Comment by edqx** [comment]
iOS doesn't have support for microphone while in another app.
