### ISSUE TITLE
[Question] Linux Selfhosting

### ISSUE THREAD

**Issue by idunnoooooo** [cybershard/auproximity#14]
is it possible to selfhost this on ubuntu vps?

**Comment by edqx** [comment]
Should just be the same as any other, if not, you can check out the self-hostable docker container.
`docker pull cybershard/auproxy:latest`
`docker run -d auproxy:latest -p 8079:8079`

**Comment by idunnoooooo** [comment]
@edqx im getting this error

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: "-p": executable file not found in $PATH": unknown.

**Comment by eliapolloniato** [comment]
@idunnoooooo i get the same error when i try to run the container with latest tag

**Comment by JohnClementine** [comment]
I have it running successfully on my Ubuntu VPS using docker. Here's my run command, you should be able to copy paste the whole thing into a terminal:

`docker run -d \
--name amongus \
--restart=always \
-p 8079:8079 \
-p 80:80 \
cybershard/auproxy:dev
`
Make sure both ports 8079 and 80 are forwarded for your server. 

Try that and let me know if it works!

**Comment by eliapolloniato** [comment]
Thank you for the response @JohnClementine, maybe i was getting that error because i tried running the docker container in a raspberry pi. All works now.

**Comment by JohnClementine** [comment]
@eliapolloniato I think containers need to be built specifically for ARM architecture to run on Pi, which this one is not. Glad to hear you're up and running though!

@idunnoooooo Try the run command I posted above and let us know if that resolves your issue 🤗

**Comment by idunnoooooo** [comment]
@JohnClementine it runs but i can't connect to site.
port 80 is occupied so i did this
```docker run -d \
--name amongus \
--restart=always \
-p 8079:8079 \
-p 8080:80 \
cybershard/auproxy:dev``` i guess thats my fault

**Comment by JohnClementine** [comment]
@idunnoooooo just confirmed with the dev, I'm mistaken and you don't need to forward port 80; only 8079.

Try this
`docker stop amongus && docker rm amongus`
^removes the old container
```
docker run -d \
--name amongus \
--restart=always \
-p 8079:8079 \
cybershard/auproxy:latest
```
Again, make sure TCP 8079 is forwarded for your VPS
Then simply visit YOUR-SERVER-IP-OR-DNS:8079 on your browser.
If that doesn't work, run `docker logs amongus` and paste the output
