### ISSUE TITLE
[BUG] Not All Players Able To Hear Each Other

### ISSUE THREAD

**Issue by pattonicole** [cybershard/auproximity#16]
**Describe the bug**
Players unable to hear each other in the lobby while in auproximity. This seems to only affect certain players. 

**To Reproduce**
Open a lobby and join a game with multiple players. Every player will be unable to hear every other player.

**Expected behavior**
All players should be able to hear each other.

**Screenshots**

**Where are you using the proximity chat?:**
Lobby was made using a mixture of Firefox and Chrome each other. It is possible that using a mixture of browsers was causing the issue.

**Additional context**
Likely related to https://github.com/cybershard/auproximity/issues/10

**Comment by pattonicole** [comment]
Providing an update here: having everyone on Firefox seems to be a workaround for now.

**Comment by edqx** [comment]
Yes there are issues with cross-browser WebRTC. We are planning a different solution which will hopefully eliminate this in the coming weeks.
