### ISSUE TITLE
[BUG] Cant hear each other

### ISSUE THREAD

**Issue by mudassirzulfiqar** [cybershard/auproximity#22]
**Describe the bug**
Hello I have tried this with my friends, but it seems that it doesn't work. Some of my friends see Disconnect in front of their name. I have also tried with several locations.

**To Reproduce**
Create a room.
Join with the name.
**Expected behavior**
Should see each other connected. and should hear each other
**Screenshots**

**Where are you using the proximity chat?:**
 - chrome, safari
 - Windows

**Additional context**

**Comment by mudassirzulfiqar** [comment]
I figured out I had a discord instance running . It is working now. Kuddos

**Comment by edqx** [comment]
nice
