### ISSUE TITLE
[BUG] Console error on voice.skeld.net

### ISSUE THREAD

**Issue by MatadorProBr** [cybershard/auproximity#28]
**Describe the bug**
Whenever I log on to the [voice.skeld.net](https://voice.skeld.net) website I am unable to play with voice proximity chat.

**To Reproduce**
1. Go to 'https://voice.skeld.net'
2. Right-click and then click 'Inspire'
3. Click on 'Console'

**Expected behavior**
The serious ideal is me and the person if we listen but for some reason we can't, and it's very rare when we can hear ourselves.

**Screenshots**
![image](https://user-images.githubusercontent.com/71022656/103924692-29987900-50f5-11eb-9b37-48f7469c8379.png)
Continuation of the same error
![image](https://user-images.githubusercontent.com/71022656/103924728-361cd180-50f5-11eb-9d98-78a141dad2de.png)

**Where are you using the proximity chat?:**
 - Browser [Microsoft Edge]
 - Platform [Windows 10]

**Additional context**
N/A

_(I don't know if you will be able to do anything about it because the site is run by skeld.net, but I know they use your plugin, and I had also reported this bug on Discord, but no one has answered me yet so I decided to send here because it is a serious problem)_

**Comment by edqx** [comment]
This isn't an issue with auproximity, but an issue with skeld.net which uses a modified version of auproximity.

**Comment by MatadorProBr** [comment]
Ok, and thanks for passing this problem on to Arkatme :)
