### ISSUE TITLE
[BUG] Can't connect to the site

### ISSUE THREAD

**Issue by Stormwolfplayz** [cybershard/auproximity#36]
**Describe the bug**
can't connect

**To Reproduce**
1. Go to the site
2. see error

**Expected behavior**
to load into site

**Where are you using the proximity chat?:**
 - Browser: chrome
 - Platform: technically i'm playing on android, but i have the proximity chat running on a chromebook

**Comment by MatadorProBr** [comment]
lol, use this site: https://aupro.xyz

**Comment by Stormwolfplayz** [comment]
oh lmao
