### ISSUE TITLE
Webpage is down

### ISSUE THREAD

**Issue by JoReSmi** [cybershard/auproximity#40]
Description
The website is down. I can't use it.

Expected behavior
I expected to be able to create a room.

Screenshots
![image](https://user-images.githubusercontent.com/81482323/112727984-4f5a4080-8ee2-11eb-90dd-15c144d3371c.png)

**Where are you using the proximity chat?:**
 - Browser chrome
 - Platform windows
Please fix this!

**Comment by edqx** [comment]
See https://aupro.xyz and also https://github.com/edqx/auproximity.

Reply within 30 seconds.

**Comment by JoReSmi** [comment]
Thanks!

**Comment by TropicSapling** [comment]
testing123 please ignore
